dataset: kitti
mode: 2d_3d_ts
exp_name: kitti_cross_modal_ts
data_path: './KITTI_DOM/KITTI_DOM_train/'
checkpoint_path_2d: './best/DIOD_KITTI.ckpt'
checkpoint_path_3d: './tmp/kitti_3d_ts/epoch_299_3d.ckpt'
num_epochs: 100
start_teacher_epoch: 0
batch_size: 4
learning_rate: 0.0005
warmup_steps: 3000
decay_rate: 0.5
decay_steps: 50000
num_slots: 45
hid_dim: 64
seed: 0
weight_recon: 1.0
weight_mask: 2.0
weight_nll: 1.0
weight_reg: 0.4
p_crop: 0.0
p_flip: 0.0
p_drop: 0.1
p_jitter: 0.0