dataset: kitti
mode: 3d_burn_in
exp_name: kitti_3d_burn_in
data_path: './KITTI_DOM/KITTI_DOM_train/'
num_epochs: 300
batch_size: 4
learning_rate: 0.0005
warmup_steps: 3000
decay_rate: 0.5
decay_steps: 50000
num_slots: 45
hid_dim: 64
seed: 0
weight_recon: 100.0
weight_mask: 1.0
weight_nll: 1.0
weight_reg: 0.3
p_crop: 0.0
p_flip: 0.0
p_drop: 0.1
p_jitter: 0.0