dataset: pd
mode: 3d_ts
exp_name: pd_3d_ts
data_path: './TRI_PD/TRI_PD_train'
supervision: 'est'
checkpoint_path_3d: './tmp/pd_3d_burn_in/epoch_299_3d.ckpt'
num_epochs: 100
start_teacher_epoch: 0
batch_size: 4
learning_rate: 0.0005
warmup_steps: 3000
decay_rate: 0.5
decay_steps: 50000
num_slots: 45
hid_dim: 64
seed: 0
weight_recon: 50.0
weight_mask: 1.0
weight_nll: 1.0
weight_reg: 0.4
p_crop: 0.4
p_flip: 0.4
p_drop: 0.4
p_jitter: 0.4